### ISSUE TITLE
Barlow Twins (Blog post)

### ISSUE THREAD

**Issue by vaisakh-m** [DeNeutoy/blog#4]
TL;DR is kinda wrong. It's a non-contrastive SSL method.

**Comment by DeNeutoy** [comment]
@vaisakh-m hello! 

Actually, I believe it is a contrastive loss function. Following the definition in this paper:

http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf

_Unlike conventional learning systems where the loss function is a sum over samples, the loss function here runs over pairs of samples. Let X^1, X^2 ∈ I be a pair of input vectors shown to thesystem. Let Y be a binary label assigned to this pair. Y = 0 if X^1 and X~2 are deemed similar, and Y = 1 if they are deemed dissimilar. Define the parameterized distance function to be learned DW between X^1, X^2 as the euclidean distance between the outputs of G_w (the function being learnt, i.e the network output)._

In this case, the Barlow Twins loss is a function of multiple pairs of datapoints, where the "positive" examples are those on the cross diagonal (i.e augmented versions of the same datapoint) and the "negative" examples are different datapoints.

In your opinion, why is it a non-constrastive loss function?

**Comment by vaisakh-m** [comment]
Hi! @DeNeutoy 

IMO the definition would have been applicable to Barlow Twins' loss function if the cross-correlation matrix had a shape of _N x N_ instead of _d x d_ (_N_ = batch size & _d_ = size of embedding vector).

Here the aim is to:
1. Increase the agreement(correlation) between the same vector components of the embedding and not the 'positive pairs'(like in Contrastive Learning). 
2. Decrease the agreement(correlation) between the different vector components of the embedding and not the 'negative pairs'(like in Contrastive Learning).

The first point can be said in other words:
- Contrastive Learning-> The embedding vectors of two different views of the _i^th_ datapoint should be invariant to the applied distortions.
- Barlow Twins:-> The vectors of _i^th_ component of the embedding(of all the datapoints) in the two different branches should be invariant of the applied distortions.
[Similarly, we can arrive at a definition for the second point.]

I don't think such a formulation can be categorized under the Contrastive Learning paradigm.

From the paper:
_Intuitively, the invariance term of the objective, by trying to equate the diagonal elements of the cross-correlation matrix to 1, makes the embedding invariant to the distortions applied. The redundancy reduction term, by trying to equate the off-diagonal elements of the cross-correlation matrix to 0, decorrelates the different vector components of the embedding. This decorrelation reduces the redundancy between output units, so that the output units contain non-redundant information about the sample._
